<?php
/**
 * @file
 */

/**
 * Implementation of hook_ctools_plugin_directory().
 */
function cns_panels_ctools_plugin_directory($module, $plugin) {
  if ($module == 'panels' && $plugin == 'display_renderers') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_ctools_plugin_api().
 *
 * Inform CTools about version information for various plugins implemented by
 * Panels.
 *
 * @param string $owner
 *   The system name of the module owning the API about which information is
 *   being requested.
 * @param string $api
 *   The name of the API about which information is being requested.
 */
function cns_panels_ctools_plugin_api($owner, $api) {
  if ($owner == 'panels' && $api == 'pipelines') {
    return array(
      'version' => 1,
      'path' => drupal_get_path('module', 'cns_panels') . '/includes',
    );
  }
}

/**
 * Implements hook_theme()
 */
function cns_panels_theme() {
  $theme['cns_panels_add_content_modal'] = array(
    'variables' => array('renderer' => NULL, 'categories' => array(), 'region' => NULL, 'category' => NULL, 'column_count' => 2),
    'path' => drupal_get_path('module', 'cns_panels') . '/templates',
    'template' => 'cns-panels-add-content-modal',
  );
  
  return $theme;
}
