<?php
/**
 * @file
 */

/**
 * Implementation of hook_ctools_plugin_directory().
 */
function cns_panels_ctools_plugin_directory($module, $plugin) {
  if ($module == 'panels' && $plugin == 'display_renderers') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_ctools_plugin_api().
 *
 * Inform CTools about version information for various plugins implemented by
 * Panels.
 *
 * @param string $owner
 *   The system name of the module owning the API about which information is
 *   being requested.
 * @param string $api
 *   The name of the API about which information is being requested.
 */
function cns_panels_ctools_plugin_api($owner, $api) {
  if ($owner == 'panels' && $api == 'pipelines') {
    return array(
      'version' => 1,
      'path' => drupal_get_path('module', 'cns_panels') . '/includes',
    );
  }
}

/**
 * Implements hook_theme()
 */
function cns_panels_theme() {
  $theme['cns_panels_add_content_modal'] = array(
    'variables' => array('renderer' => NULL, 'categories' => array(), 'region' => NULL, 'category' => NULL, 'column_count' => 2),
    'path' => drupal_get_path('module', 'cns_panels') . '/templates',
    'template' => 'cns-panels-add-content-modal',
  );
  
  $theme['cns_panels_add_content_link'] = array(
    'variables' => array('renderer' => NULL, 'region' => NULL, 'content_type' => NULL),
    'path' => drupal_get_path('module', 'cns_panels') . '/templates',
    'template' => 'cns-panels-add-content-link',
  );
  
  return $theme;
}

/**
 * Implements template_process_HOOK().
 */
function template_process_cns_panels_add_content_modal(&$vars) {
  //$custom = ctools_get_content_type('custom');
  $custom = ctools_content_get_subtypes('custom');
  $custom = $custom['custom'];
  $custom += array(
    'type_name' => 'custom',
    'subtype_name' => 'custom',
  );
  
  // Change the title to "Images and Text"
  $custom['title'] = t("Images and Text");
 
  $vars['custom_link'] = theme('cns_panels_add_content_link', array('renderer' => $vars['renderer'], 'region' => $vars['region'], 'content_type' => $custom));
}

/**
 * Preprocess the add content link used in the modal.
 */
function template_preprocess_cns_panels_add_content_link(&$vars) {
  module_load_include('inc', 'panels', 'includes/add-content');
  
  template_preprocess_panels_add_content_link($vars);
}

/**
 * Implements hook_page_alter()
 */
function cns_panels_page_alter(&$page) {
  drupal_add_css(drupal_get_path('module', 'cns_panels') . '/css/cns_panels.css');
}
